name: Update Genshin Widget

on:
  workflow_dispatch:

  schedule:
    # Every 3 hours
    - cron: "0 */3 * * *"

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Genshin Widget Updater
        env:
          GENSHIN_UID: ${{ secrets.GENSHIN_UID }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: node enkaUser.js